### ISSUE TITLE
Add Windows support

### ISSUE THREAD

**Issue by anthonychu** [anthonychu/azure-functions-deno-worker#1]
`denofunc` seems to be having trouble resolving path to `func`.

https://github.com/anthonychu/azure-functions-deno-worker/blob/ccf2640/denofunc.ts#L120

```
> denofunc start
Generating functions...
Cleaning function folders...
Deleting folder hello_world.
Generating function folders...
Generating file hello_world/function.json.
Running command: deno bundle --unstable worker.ts worker.bundle.js
Bundling file:///D:/git/temp/20200513-test-deno/worker.ts
Emitting bundle to "worker.bundle.js"
1564236 bytes emmited.
Starting Azure Functions Core Tools: func start
error: Uncaught NotFound: The system cannot find the file specified. (os error 2)
    at unwrapResponse ($deno$/ops/dispatch_json.ts:43:11)
    at Object.sendSync ($deno$/ops/dispatch_json.ts:72:10)
    at Object.run ($deno$/ops/process.ts:45:10)
    at Object.run ($deno$/process.ts:118:15)
    at runFunc (denofunc.ts:125:23)
    at async denofunc.ts:18:5
```

Also, `chmod` doesn't work. Need to investigate if this is needed on Windows to turn on execute bit for the deno binary to be deployed properly. Not needed once this fix is fully deployed to Azure: https://github.com/Azure/azure-functions-host/issues/5696

https://github.com/anthonychu/azure-functions-deno-worker/blob/ccf2640/denofunc.ts#L63

**Comment by aadamsx** [comment]
Since #2 was fixed, I'm able to install, but according to this I won't get far on Win 10 right?

**Comment by anthonychu** [comment]
Right. Hope to find some time over the next week to track those down. Feel free to give it a try and see if you hit the same issues. It should work in WSL though.

**Comment by anthonychu** [comment]
Chmod problem fixed in #5.

I wasn't able to reproduce my path issues on another Windows environment. Perhaps the first one I tried had something misconfigured. Will leave this open for a couple of days while I look for another Windows box to confirm.

@aadamsx Let me know if this works for you.

**Comment by aadamsx** [comment]
Seems to work for me.  Thanks.

**Comment by anthonychu** [comment]
Thanks @aadamsx. I'll close this for now.
