### ISSUE TITLE
Need to upgrade std for Deno 1.2.0

### ISSUE THREAD

**Issue by horihiro** [anthonychu/azure-functions-deno-worker#18]
There seems some breaking change on Deno from 1.1.x to 1.2.0.
It needs to upgrade std from 0.60.0 or before to 0.61.0.

- [ ] denofunc
- [ ] deno-zip
- [x] oak
https://github.com/oakserver/oak/issues/200

**Comment by anthonychu** [comment]
Fixed with https://github.com/anthonychu/azure-functions-deno-worker/commit/0d4d073a1903c2dd9623c40323e8a516a6d6c196

**Comment by horihiro** [comment]
Thanks @anthonychu !
