### ISSUE TITLE
Property 'getIterator' does not exist on type 'ReadableStream<R>'.

### ISSUE THREAD

**Issue by justinmchase** [anthonychu/azure-functions-deno-worker#47]
Installing this script with the latest version of deno produces this error:

> Check https://raw.githubusercontent.com/anthonychu/azure-functions-deno-worker/v0.8.0/denofunc.ts
> error: TS2339 [ERROR]: Property 'getIterator' does not exist on type 'ReadableStream<R>'.
>   return res.readable.getIterator();

```sh
$ deno --version
deno 1.16.1 (release, x86_64-unknown-linux-gnu)
v8 9.7.106.2
typescript 4.4.2
```

**Comment by justinmchase** [comment]
It must be in a dependency, I'm not sure how to track it down because the code doesn't appear in this repo at all.

But adding `--no-check` works around the issue for now.

**Comment by justinmchase** [comment]
Ok it actually has the error at runtime too, there it has more info:
```
    at https://deno.land/std@0.67.0/async/pool.ts:45:23
```

**Comment by horihiro** [comment]
The module which depends on `std@0.67.0` is [`oak@6.1.0`](https://deno.land/x/oak@v6.1.0/deps.ts), which [`azure_functions@v0.8.0/worker_deps.ts`](https://deno.land/x/azure_functions@v0.8.0/worker_deps.ts) depend on.
So to resolve this issue, oak needs to be updated to `6.4.2` (this version depends on `std@0.84.0`) at least.

`ReadableStream.getIterator` was [removed from Deno@1.16.0](https://github.com/denoland/deno/releases/tag/v1.16.0), and `std@0.84.0` and later already removed it from [`async/pool.ts`](https://deno.land/std@0.84.0/async/pool.ts#L45).
